//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketSummaryWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProspectDBContext : DbContext
    {
        public ProspectDBContext()
            : base("name=ProspectDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProspectData> ProspectDatas { get; set; }
        public virtual DbSet<ProspectDataSearchCriteria> ProspectDataSearchCriterias { get; set; }
        public virtual DbSet<ProspectSummary> ProspectSummaries { get; set; }
    }
}
